<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>31bfb6d4-666e-4d0b-9d4d-82baaca18efa</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.1" />
    <PackageReference Include="Microsoft.Playwright" Version="1.57.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WizardSchemaExtractor\WizardSchemaExtractor.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Handlers\" />
    <Folder Include="Steps\" />
    <Folder Include="Schemas\" />
  </ItemGroup>

</Project>
